### PR TITLE
feat: Adding support for poetry 1.8.0 - 1.8.2

### LINKED ISSUE #371: Support Poetry 1.8.*
## Describe the Enhancement

The current buildpack doesn't work with 1.8.* poetry version.

## Possible Solution

Add support for 1.8.* versions

## Motivation

To be able to use latest poetry.

### PR DESCRIPTION
**Pull request by radoshi**
## Summary
Fixes #371 This PR adds support for poetry versions 1.8.0, 1.8.1, and 1.8.2.

## Use Cases
See summary.

I do not believe an integration test is necessary. Please feel free to guide me if this is incorrect.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by radoshi** [comment]
Please note: Integration tests are failing locally, both before and after the change. I'm happy to get some guidance on fixing these, but they currently end up timing out.

Unit tests are fine locally.

**Comment by dmitry-mightydevops** [comment]
can we get attention to this PR and get it approved/merged?

**Comment by nairb774** [comment]
@arjun024 Would you be able to help us get traction on this PR?

I wouldn't normally @ someone, but I saw you were recently reviewing PRs for this repo, and thought you might be able to help out with getting traction on this version update. Thanks!

**Comment by arjun024** [comment]
https://github.com/paketo-buildpacks/python/releases/tag/v2.19.0

**Pull request closed without merging**
